### ISSUE TITLE
Add docker image built for arm64

### ISSUE THREAD

**Issue by tomerip** [itairaz1/israeli-bank-firefly-importer#131]
Add automatic build option for the arm64 platform so that people running on raspberry pi can use the pre-built docker images from `itair86/israel-bank-firefly-importer`

**Comment by itairaz1** [comment]
Puppeteer has issues with arm 
I couldn't find a way to run it with ARM, in my mac (apple silicon) I'm using Rosette
In my raspberry pi I'm running it with home assistant using [this project](https://github.com/itairaz1/israeli-bank-firefly-importer-hass-addon).
If you found a way, I will be happy to add
