### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by Fannangir** [itairaz1/israeli-bank-firefly-importer#37]
Hi,
This is a question actually, not an issue.
I would like to run the importer as a docker container (have a running docker on my synology).
I believe (from some reading) that it is possible to run NPM in a docker.
Could you (if possible) please help with such installation?
Thanks in advance.

**Comment by itairaz1** [comment]
Hi @Fannangir ,
You can build the current docker using the Dockerfile in the repo
or, you can use this image: `itair86/israel-bank-firefly-importer:1.2.3`
I will update the readme and add docker to the build process
Please let me know if you have more questions

**Comment by Fannangir** [comment]
Thank you very much for the explanation.
As you have plans to add docker build process to the readme, I can hold it until you are ready.
If possible, please comment when you have documented the process.
I will follow the documentation.
Thanks.

**Comment by Fannangir** [comment]
@itairaz1 Did you have the chance to look into docker instructions?
Thanks.
